hf_dataset_name = "rotten_tomatoes"
batch_size = 32
num_epochs = 100

[gpt]
num_blocks = 7
vocab_size = 41
max_seq_len = 12
embed_pdrop = 0.1

[optimizers]
lr = 0.001
wd_lr = 0.001
clip_grad_norm = 1.0
weight_decay = 0.1
adam_beta1 = 0.9
adam_beta2 = 0.999

[logging]
steps_per_epoch = 1000
ema_decay = 0.33

[gpt.attention]
embed_dim = 128
num_heads = 4
attn_drop_prob = 0.1
resid_drop_prob = 0.1
